name: Gitleaks Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source=. --verbose --report-format=json --report-path=report.json --log-opts="--all"